### ISSUE TITLE
accelerate launch test.py error

### ISSUE THREAD

**Issue by AmpleFiled** [lucidrains/vector-quantize-pytorch#112]
I can run the README code in a single GPU, but get error when i run the multi GPU distribution training 
Traceback (most recent call last):
  File "/vepfs/home/tianbo/sora/test.py", line 77, in <module>
    trainer = VideoTokenizerTrainer(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_custom_utils/accelerate_utils.py", line 95, in __init__
    _orig_init(self, *args, **kwargs)
  File "<@beartype(magvit2_pytorch.trainer.VideoTokenizerTrainer.__init__) at 0x7fa710968790>", line 314, in __init__
  File "/vepfs/home/tianbo/sora/magvit2_pytorch/trainer.py", line 202, in __init__
    self.has_multiscale_discrs = self.model.has_multiscale_discrs
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DistributedDataParallel' object has no attribute 'has_multiscale_discrs'

**Comment by lucidrains** [comment]
@AmpleFiled the issue is actually in the magvit2 repo, should be [fixed](https://github.com/lucidrains/magvit2-pytorch/commit/b17e1aedc1885af3beb448cd22afb397384c959d)
