### ISSUE TITLE
How to freeze codebook ?

### ISSUE THREAD

**Issue by BMontens** [lucidrains/vector-quantize-pytorch#68]
I'm trying to train a network with a predetermined codebook, but I can't get the codebook to stay the same. I have tried to set `vq_module.eval()` but I then get the error:
```
Traceback (most recent call last):
  File "/media/USRNAME/Storage/Code/VQCode.py", line 110, in <module>
    avg_loss = train_one_epoch()
  File "/media/USRNAME/Storage/Code/VQCode.py", line 24, in train_one_epoch
    loss.backward()
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Right now I'm just resetting its value in the forward pass each time.

**Comment by lucidrains** [comment]
@BMontens could you try setting `ema_update = False` when instantiating?

**Comment by BMontens** [comment]
It worked! Thank you!

**Comment by lucidrains** [comment]
@BMontens wait lol

ok, how would you ideally like to use it?

maybe something like `vq(codes, ..., freeze_codebook = True)` ?

**Comment by BMontens** [comment]
Well, there already is an argument "learnable_codebook" so I thought that did it (could you explain what it does btw). But yes, having a way to make a frozen VQ would be great.

Right now, what I'm doing is:
```
self.vq = VectorQuantize(dim = dim, codebook_size = size, ema_update = False)
self.vq._codebook.embed = torch.tensor(codes, device="cuda:0")
```

**Comment by lucidrains** [comment]
also added a setter method for the codebook, so you can just do `self.vq.codebook = torch.tensor(codes)`

**Comment by BMontens** [comment]
Yeah, it worked! Amazing!

**Comment by Nidelor** [comment]
If you do a two-stage training where you train a codebook in the first stage and then want to freeze your codebook for the second stage, does that mean you create another codebook with `freeze_codebook = True` and you copy the codes from your trained codebook into the second one you just created?

```python
trained_codebook = VectorQuantizer()

# train codebook during first stage

new_codebook = VectorQuantizer(freeze_codebook = True)
new_codebook.codebook = trained_codebook.codebook

# second stage of training where I want to use the frozen codebook
```

Because I've tried something like this and it looks like my network doesn't learn anything while if I remove the VQ part the loss curves are going down so I don't know where I went wrong or if this is the proper way to do it

**Comment by lucidrains** [comment]
@AlecMRogers you just have to pass `freeze_codebook = True` on .forward

**Comment by lucidrains** [comment]
@AlecMRogers oh excuse me i didn't read your question carefully. do you mean to be able to freeze some codes but not others? would passing in indices of codes you wish to be frozen work?

**Comment by AlecMRogers** [comment]
Yes: basically, I am trying to freeze some code book vectors if they have been reliably close to the input. The ability to set a per-vector learning rate or gradient might be even more flexible, which would allow annealing vectors individually (and which would allow freezing by setting that to zero). 

Finding a good measure of "reliably close" is something I am not clear about, but at least turning off learning for some codes handles training with exponential decay updating when the input space may not represent the given source again for some time.

**Comment by lucidrains** [comment]
@AlecMRogers yes I agree that would be interesting research. maybe for starters could pass in learning rate for the EMA update

let me think about it

**Comment by lucidrains** [comment]
@AlecMRogers could you open a new issue for this? i may forget with all that is going on

**Comment by lucidrains** [comment]
@AlecMRogers still want this or no?

**Comment by AlecMRogers** [comment]
I'm trying to set the grad to 0 after doing   learnable_codebook = True and   ema_update=False.
Ten I wouldn't have to create a request.

But I get: 
self.vq.codebook.grad
<input>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)

**Comment by lucidrains** [comment]
@AlecMRogers try asking Gemini 2.5 about that error

also, I don't think that would stop the EMA from updating the code

**Comment by lucidrains** [comment]
@AlecMRogers I can just get it built for you, it is interesting enough

**Comment by AlecMRogers** [comment]
Created "Freeze some elements of a codebook #210".

It would still be nice to set a hook for the gradient, though, since Im thinking that knowledge of the updates to the gradient might help me know when a particular vector in the codebook should be frozen in the first place.

**Comment by lucidrains** [comment]
@AlecMRogers yup, can expose a hook
